plugins {
    id "com.android.application"
    id "com.chaquo.python"
}

android {
    namespace "org.nature"
    compileSdkVersion 35

    defaultConfig {
        applicationId "org.nature"
        minSdkVersion 35
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a"
        }

    }

    compileOptions {
        sourceCompatibility 17
        targetCompatibility 17
    }

}

chaquopy {
    sourceSets.named("main") {
        srcDirs = ["src/main/python"]
    }
    defaultConfig {
        version = "3.14"
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.alibaba:fastjson:1.2.83"
}